apiVersion: security.openshift.io/v1
allowPrivilegeEscalation: true
defaultAddCapabilities:
- CHECKPOINT_RESTORE
- SETPCAP
# 2024-09-04:
# Found that groups is needed when using OpenShift Local 4.16.0. Not sure with OpenShift (not Local).
# This was not needed when I used OpenShift Local 4.14.12.
groups:
- system:authenticated
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: criu-scc is based on the restricted SCC but removes any restrictions
      that prevent the restore image from running successfully.
  generation: 1
  name: liberty-to-openshift-instanton-scc
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsNonRoot
  uid: 1001
seLinuxContext:
  type: MustRunAs
